import type { Metadata } from "next";
import "../styles/globals.css";
import { Providers } from "./Providers";
import { Inter, Roboto } from "@/app/components/static/Fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,children,
}: Readonly<{
  params:{locale:string},
  children: React.ReactNode;
}>) {
  const { locale } = params;
  return (
    <html lang={locale} className={Roboto.className + ' ' + Inter.variable + ' ' + Roboto.variable}>
      <Providers locale={locale}>
        {children}
      </Providers>
    </html>
  );
}
